# basic options
title: Impredicative Fibrations
author: Konstantinos Brilakis
email: kon.bril@gmail.com
description: Personal blog
twitter_username: jekyllrb
github_username: superhaNds

# Build settings
markdown: kramdown
theme: minima
